# Generated by Django 3.2.25 on 2024-06-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='profile_image',
        ),
    ]
